[build]
  functions = "./functions"
  command = "yarn build"
  publish = "public"

[dev]
  # Local dev command. A.k.a npm start
  command = "yarn dev"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


[[headers]]
  for = "/404.html"
  [headers.values]
    Cache-Control = "max-age=300"
