[build]
  functions = "./functions"
  command = "yarn build"
  publish = "public"

[build.environment]
  NETLIFY_USE_YARN = "true"

[dev]
  # Local dev command. A.k.a npm start
  command = "yarn dev"
