[build]
  functions = "./functions"
  command = "yarn build"
  publish = "public"

[dev]
  # Local dev command. A.k.a npm start
  command = "yarn dev"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; prefetch-src 'self'; connect-src 'self' *.google-analytics.com; manifest-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'none'; frame-src https://www.youtube.com *.google.com; frame-ancestors 'none'; form-action 'none'; script-src 'self' *.google-analytics.com maps.googleapis.com 'unsafe-inline';img-src data: 'self' *.google-analytics.com maps.gstatic.com *.googleapis.com *.ggpht *.ytimg.com;object-src 'none';"
# require-trusted-types-for 'script';

[[headers]]
  for = "/*.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "404.html"
  [headers.values]
    Cache-Control = "max-age=300"
