name: "Submodule Update - branch: dev"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: dev
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: submodule Update
        run: |
          # git submodule sync
          git submodule update --remote
          # --init --recursive

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: |
          echo "Changes exist"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "remote data update"

      - name: Push changes
        if: steps.changes.outputs.changed == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      #- name: Trigger deploy
      #  if: steps.changes.outputs.changed == 1
      #  run: |
      #    curl \
      #      -X POST \
      #      -H "Accept: application/vnd.github.v3+json" \
      #      -u ${{ secrets.API_TOKEN }} \
      #      https://api.github.com/repos/alextim/s-bars/actions/workflows/autodeploy.yml/dispatches \
      #      -d '{"ref":"dev"}'

      - name: No Changes
        if: steps.changes.outputs.changed == 0
        run: |
          echo "No Changes"
